In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
df.shape

(898, 35)

In [5]:
X = df.drop("Class" , axis =1)
y = df["Class"]

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [7]:
X

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,255403,1925.3650,691.8453,477.1796,0.7241,570.2536,0.9785,261028,0.7269,1.4499,...,-0.1398,2.2423,2.3704,2.7202,-25296416768,-19168882688,-18473392128,49.0869,43.0422,42.4153
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,0.5611,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502
895,254330,1926.7360,747.4943,435.6219,0.8126,569.0545,0.9925,256255,0.7240,1.7159,...,0.2665,2.2759,2.5090,2.6951,-22242772992,-19594921984,-17592152064,44.1325,40.7986,40.9769
896,238955,1906.2679,716.6485,441.8297,0.7873,551.5859,0.9604,248795,0.6954,1.6220,...,0.5325,2.6769,2.6874,2.7991,-26048595968,-21299822592,-19809978368,51.2267,45.7162,45.6260
897,343792,2289.2720,823.8438,534.7757,0.7607,661.6113,0.9781,351472,0.6941,1.5405,...,0.4318,2.5138,3.0369,3.0865,-31983476736,-20482514944,-21219354624,47.3454,38.6966,39.6738

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [9]:
# split

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(

    X , y , test_size =0.2 , random_state = 42
)

In [10]:
X_train

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,169573,1548.9830,594.8965,364.4516,0.7904,464.6580,0.9932,170738,0.8245,1.6323,...,-0.6257,2.4879,2.1186,2.4125,-35847098368,-33293408256,-27052677120,69.5829,67.4267,61.7498
270,102142,1223.5020,441.7251,296.5040,0.7412,360.6262,0.9863,103559,0.7847,1.4898,...,-0.5385,3.7325,3.9749,3.0696,-20307597312,-20240594944,-18247018496,68.7153,69.4312,65.9034
860,212397,1773.1410,649.3710,418.6798,0.7644,520.0310,0.9773,217331,0.7605,1.5510,...,0.1680,2.8597,2.8887,3.0498,-21660262400,-16450807808,-15513940992,50.1400,43.9826,43.0455
435,441826,2486.4771,942.0581,603.1290,0.7682,750.0336,0.9948,444138,0.8075,1.5620,...,1.7484,7.9695,9.3755,7.3022,-36332118016,-32863416320,-37779701760,43.0456,41.0627,43.2121
102,212744,1720.3030,628.2148,432.3847,0.7254,520.4556,0.9918,214501,0.7818,1.4529,...,-0.2504,1.9579,2.1380,2.4907,-28291532800,-27781709824,-24325011456,55.4153,54.8434,52.6176

In [11]:
y_train

array([6, 5, 2, 3, 1, 3, 2, 0, 0, 5, 4, 5, 2, 1, 2, 4, 4, 4, 5, 4, 6, 6,
       4, 2, 5, 5, 5, 4, 4, 2, 4, 6, 5, 6, 2, 0, 5, 1, 4, 3, 1, 2, 6, 2,
       2, 3, 2, 5, 2, 4, 0, 2, 6, 4, 2, 1, 4, 6, 5, 5, 5, 5, 3, 4, 3, 4,
       3, 6, 5, 2, 4, 1, 1, 3, 0, 3, 3, 4, 6, 2, 1, 4, 4, 5, 4, 5, 6, 2,
       3, 5, 2, 2, 4, 6, 2, 6, 1, 6, 2, 5, 5, 1, 1, 3, 6, 1, 2, 0, 4, 2,
       2, 4, 4, 3, 1, 2, 0, 4, 4, 1, 5, 3, 5, 1, 2, 2, 5, 3, 1, 4, 4, 2,
       0, 4, 1, 3, 0, 2, 4, 6, 0, 2, 3, 3, 0, 3, 6, 5, 2, 4, 5, 3, 5, 0,
       5, 4, 1, 0, 2, 2, 2, 5, 0, 2, 4, 4, 2, 4, 5, 5, 3, 4, 4, 2, 4, 5,
       2, 2, 4, 5, 1, 1, 4, 5, 1, 1, 4, 1, 4, 1, 2, 6, 6, 6, 4, 5, 1, 0,
       3, 0, 0, 2, 2, 5, 4, 5, 4, 2, 4, 5, 4, 2, 5, 5, 5, 3, 2, 4, 2, 5,
       0, 0, 3, 2, 4, 6, 5, 3, 2, 6, 6, 5, 2, 4, 0, 2, 0, 2, 2, 4, 5, 6,
       4, 2, 6, 4, 2, 2, 1, 4, 4, 6, 2, 2, 5, 3, 4, 1, 1, 5, 4, 2, 1, 6,
       2, 2, 5, 4, 2, 1, 5, 1, 1, 5, 2, 2, 0, 6, 4, 5, 3, 4, 1, 2, 5, 1,
       2, 5, 5, 4, 4, 2, 2, 5, 1, 5, 6, 6, 5, 3, 2, 5, 2, 3, 2, 2, 0, 2,
       3, 4, 4, 2, 2, 6, 5, 1, 6, 0, 6, 2, 4, 1, 4, 4, 5, 6, 5, 2, 2, 2,
       2, 0, 6, 1, 1, 5, 0, 2, 6, 1, 4, 3, 6, 2, 0, 5, 5, 5, 3, 4, 0, 2,
       2, 5, 4, 5, 5, 1, 2, 4, 0, 1, 2, 2, 4, 6, 2, 1, 5, 2, 2, 5, 5, 5,
       5, 4, 4, 6, 0, 6, 1, 5, 2, 0, 4, 0, 6, 5, 4, 5, 4, 2, 4, 2, 0, 6,
       3, 6, 2, 2, 0, 6, 3, 4, 6, 5, 5, 2, 5, 5, 4, 6, 5, 4, 6, 1, 5, 1,
       6, 5, 5, 1, 2, 5, 1, 3, 3, 4, 1, 0, 1, 3, 6, 2, 5, 5, 0, 5, 0, 4,
       2, 2, 5, 4, 5, 5, 5, 2, 5, 2, 3, 1, 5, 5, 4, 4, 1, 1, 5, 6, 5, 2,
       4, 2, 2, 1, 5, 5, 1, 6, 2, 5, 2, 2, 3, 1, 2, 2, 3, 2, 3, 5, 1, 5,
       3, 5, 5, 6, 2, 5, 6, 5, 6, 5, 5, 5, 3, 6, 4, 2, 5, 4, 4, 1, 2, 5,
       5, 5, 3, 6, 5, 2, 5, 5, 2, 5, 3, 5, 2, 2, 5, 5, 2, 3, 3, 2, 6, 5,
       4, 2, 4, 5, 6, 6, 6, 5, 5, 5, 5, 4, 6, 4, 1, 2, 5, 1, 4, 0, 4, 2,
       5, 5, 5, 6, 5, 1, 4, 2, 4, 5, 4, 4, 5, 2, 3, 3, 5, 2, 0, 5, 5, 5,
       5, 4, 5, 5, 1, 5, 4, 3, 4, 0, 0, 2, 1, 0, 5, 2, 4, 3, 2, 3, 5, 3,
       4, 4, 1, 0, 4, 5, 1, 6, 4, 0, 0, 1, 0, 4, 3, 2, 5, 2, 5, 0, 2, 5,
       5, 5, 2, 5, 2, 5, 4, 4, 6, 2, 2, 1, 4, 5, 3, 5, 4, 5, 1, 4, 3, 0,
       6, 4, 1, 2, 0, 5, 4, 3, 4, 2, 1, 2, 4, 2, 5, 2, 0, 2, 4, 3, 2, 2,
       6, 6, 5, 6, 4, 6, 4, 6, 2, 4, 4, 5, 2, 5, 5, 4, 5, 4, 0, 4, 4, 6,
       5, 2, 0, 2, 4, 1, 2, 2, 3, 6, 3, 4, 2, 5, 2, 5, 1, 5, 6, 1, 3, 1,
       4, 2, 2, 4, 1, 5, 0, 5, 1, 1, 2, 6, 3, 1])

In [12]:
X_test

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
331,143957,1452.2620,523.1368,352.3305,0.7392,428.1259,0.9844,146236,0.7746,1.4848,...,-0.3565,4.1478,3.4278,2.4134,-36987568128,-34249711616,-23752157184,77.3446,75.2287,62.9057
638,260563,1975.3740,762.5055,437.8510,0.8187,575.9854,0.9871,263977,0.6648,1.7415,...,0.3581,7.7778,16.2644,3.6606,-2424508160,-4791147520,-8197618688,16.2304,22.3860,28.8860
326,154245,1503.5980,546.4366,361.8018,0.7494,443.1601,0.9883,156070,0.7420,1.5103,...,0.3657,2.4202,2.9624,3.0045,-14960579584,-14010061824,-14057613312,48.2049,46.8561,46.4054
848,317794,2280.9690,875.5868,525.3380,0.8000,636.1037,0.9016,352462,0.6484,1.6667,...,0.3719,2.2682,2.1522,2.9676,-47417053184,-39451316224,-33127270400,58.7696,54.0476,50.8977
39,402279,2295.8630,798.9365,643.2753,0.5931,715.6797,0.9936,404887,0.7867,1.2420,...,1.9477,5.5889,12.5304,9.9496,-30746945536,-32178810880,-35126345728,43.7705,45.6162,46.3010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,283770,2096.7639,775.8751,468.8516,0.7968,601.0883,0.9737,291436,0.6751,1.6548,...,0.8440,11.0456,12.1213,6.1299,-4560918528,-7281993216,-9060293632,20.5245,25.8721,29.4805
25,381508,2239.7891,734.2203,666.2502,0.4202,696.9584,0.9919,384642,0.7398,1.1020,...,2.0740,6.6729,10.5392,9.3474,-25635362816,-25228310528,-28113027072,41.0071,41.1774,41.5364
84,253276,1961.0400,740.2677,437.3487,0.8068,567.8741,0.9822,257864,0.7493,1.6926,...,-0.1425,2.0920,1.9879,2.1549,-45574098944,-41109114880,-35898662912,64.4454,61.4443,58.3921
10,364495,2216.4900,790.9014,590.7698,0.6649,681.2411,0.9949,366374,0.7658,1.3388,...,0.9283,3.0514,4.3653,6.0898,-41679380480,-40727969792,-37574615040,52.7269,52.9888,50.3108
332,156030,1566.9790,595.6793,384.2388,0.7641,445.7169,0.9118,171132,0.6319,1.5503,...,-0.3529,2.5952,2.3904,2.6668,-33837977600,-33563627520,-25646532608,70.7212,71.3609,63.4659

In [13]:
y_test

array([2, 5, 2, 6, 0, 2, 3, 2, 2, 1, 1, 2, 2, 2, 4, 4, 6, 5, 6, 1, 5, 4,
       2, 4, 5, 2, 0, 6, 0, 5, 6, 1, 2, 4, 2, 5, 0, 2, 2, 5, 1, 4, 5, 5,
       2, 1, 1, 2, 2, 5, 4, 3, 2, 6, 2, 4, 1, 2, 2, 0, 3, 6, 2, 2, 2, 6,
       1, 2, 4, 4, 2, 2, 4, 6, 3, 4, 2, 4, 5, 4, 2, 1, 4, 4, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 1, 2, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 4, 4, 4, 6, 1, 5, 5, 4, 4, 2, 5, 1, 5, 5, 6, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 6, 6, 5, 2, 0, 0, 5, 6, 4, 6, 1,
       1, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 4, 2, 4, 1, 6, 5, 6, 6, 5,
       0, 1, 0, 2])

In [14]:
# Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() # instance create of class StandardScaler

X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [15]:
X_train_scale

array([[ 0.58688241,  0.77313761,  0.65494348, ...,  0.30093727,
        -0.16212317, -0.02461782],
       [ 0.3914469 ,  0.71185715,  1.13717993, ..., -1.80898088,
        -1.46032963, -1.34892074],
       [-2.06406201, -2.47260549, -2.61727944, ...,  0.29158724,
         0.32348907,  0.24572657],
       ...,
       [-0.8299155 , -0.72527788, -0.73488935, ...,  0.02780714,
        -0.3163686 , -0.44177804],
       [ 1.30943154,  1.02019277,  1.29642401, ..., -0.41235787,
        -0.5222101 , -0.42641305],
       [-0.82667985, -0.85456781, -0.88171807, ...,  0.35510789,
         0.44927523,  0.44102602]], shape=(718, 34))

In [16]:
X_test_scale

array([[-1.46809512, -1.51044055, -1.61098268, ...,  1.71568954,
         1.88635897,  1.38986445],
       [-0.38078401, -0.23043153,  0.05028916, ..., -2.07608033,
        -1.83884423, -1.74766326],
       [-1.37216304, -1.38482587, -1.44927691, ..., -0.09225422,
        -0.11379811, -0.13190525],
       ...,
       [-0.44873279, -0.26550556, -0.1040461 , ...,  0.91537148,
         0.9146128 ,  0.97358961],
       [ 0.58834638,  0.3595581 ,  0.247363  , ...,  0.18830878,
         0.3185332 ,  0.22827726],
       [-1.35551852, -1.22973814, -1.10752165, ...,  1.30474726,
         1.61369423,  1.4415299 ]], shape=(180, 34))

In [17]:
y_train.shape

(718,)

### Deep Learning

In [18]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

In [19]:
import torch  # short Pytorch - torch

print(torch.__version__)
print(torch.cuda.is_available())

2.13.0+cu126
True

In [20]:
# Convert data into Tensors

import torch.nn as nn

X_train_tensor = torch.tensor(X_train_scale , dtype = torch.float32)
X_test_tensor = torch.tensor(X_test_scale , dtype = torch.float32)
y_train_tensor = torch.tensor(y_train , dtype = torch.long )
y_test_tensor = torch.tensor(y_test , dtype = torch.long)

In [21]:
# Loss fnx for classification problem Cross entropy , target value expect long format that's why - torch.long

In [22]:
type(y_train)

numpy.ndarray

In [23]:
# Tensor Data set - To define Dataset, access from Memory(RAM)

In [24]:
from torch.utils.data import TensorDataset , DataLoader

#train_dataset = TensorDataset(in_features , op_features)
#instance create for class TensorDataset

train_dataset = TensorDataset(X_train_tensor , y_train_tensor)
test_dataset = TensorDataset(X_test_tensor , y_test_tensor)

In [25]:
# Data Loader - To define how the data will be loaded for traning

In [26]:
train_loader = DataLoader(train_dataset , batch_size =32 , shuffle = True)
test_loader = DataLoader(test_dataset , batch_size = 32)

In [27]:
X_train.shape[1]

34

### Build Model

In [28]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN , self).__init__()

        self.model = nn.Sequential(

            # 1st hidden layer
            # nn.AF(in_feature , op_feature),

            nn.Linear(X_train.shape[1] , 64),
            nn.ReLU(),

            # 2nd hidden layer

            nn.Linear(64,64),
            nn.ReLU(),

            #O/P Layer

            nn.Linear(64,7)
            # Softmax() - by deafult cross entropy - Cost fnx - there apply
            
            
        )

    def forward(self , x):
        return self.model(x)

In [29]:
import torch.optim as optim

model = ANN()

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

### Train Model

In [34]:
epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for xb , yb in train_loader:

        optimizer.zero_grad() # for each batch fresh gradient compute, dont accumualte value of graident of previous batch
        
        output = model(xb)  #forward propgation... predicted value for this batch
        loss = criterion(output, yb)  # Loss compute
        loss.backward() # Gradient compute automatically
        optimizer.step() # learn params update

        running_loss += loss  # Total running loss cal for all batches(23) in 1 epoch

    train_loss = running_loss/len(train_loader)  # Avg loss per batch for 1 epoch
        
    print(f"epoch = {epoch}/{epochs} , loss = {train_loss}")

epoch = 0/100 , loss = 0.004824623465538025
epoch = 1/100 , loss = 0.007874419912695885
epoch = 2/100 , loss = 0.0051274849101901054
epoch = 3/100 , loss = 0.0052550421096384525
epoch = 4/100 , loss = 0.004760566167533398
epoch = 5/100 , loss = 0.004686618223786354
epoch = 6/100 , loss = 0.004083449952304363
epoch = 7/100 , loss = 0.0033673751167953014
epoch = 8/100 , loss = 0.004196315538138151
epoch = 9/100 , loss = 0.008600560016930103
epoch = 10/100 , loss = 0.019333114847540855
epoch = 11/100 , loss = 0.008212568238377571
epoch = 12/100 , loss = 0.00909089669585228
epoch = 13/100 , loss = 0.003727551084011793
epoch = 14/100 , loss = 0.004381523933261633
epoch = 15/100 , loss = 0.0033755467738956213
epoch = 16/100 , loss = 0.0035085587296634912
epoch = 17/100 , loss = 0.004486429039388895
epoch = 18/100 , loss = 0.0026868435088545084
epoch = 19/100 , loss = 0.002921786392107606
epoch = 20/100 , loss = 0.003486697329208255
epoch = 21/100 , loss = 0.003282645484432578
epoch = 22/100 , loss = 0.0026290020905435085
epoch = 23/100 , loss = 0.002773730084300041
epoch = 24/100 , loss = 0.0028064658399671316
epoch = 25/100 , loss = 0.0025540529750287533
epoch = 26/100 , loss = 0.00250077317468822
epoch = 27/100 , loss = 0.0023428958375006914
epoch = 28/100 , loss = 0.002843858441337943
epoch = 29/100 , loss = 0.0037551100831478834
epoch = 30/100 , loss = 0.0031033065170049667
epoch = 31/100 , loss = 0.00368553982116282
epoch = 32/100 , loss = 0.0027327719144523144
epoch = 33/100 , loss = 0.003654878120869398
epoch = 34/100 , loss = 0.002895935671404004
epoch = 35/100 , loss = 0.00191385461948812
epoch = 36/100 , loss = 0.002147484105080366
epoch = 37/100 , loss = 0.002226330805569887
epoch = 38/100 , loss = 0.001755670178681612
epoch = 39/100 , loss = 0.001864816527813673
epoch = 40/100 , loss = 0.0020165559835731983
epoch = 41/100 , loss = 0.0017039886442944407
epoch = 42/100 , loss = 0.0016821936005726457
epoch = 43/100 , loss = 0.001616582740098238
epoch = 44/100 , loss = 0.0016742029692977667
epoch = 45/100 , loss = 0.0016741700237616897
epoch = 46/100 , loss = 0.0016223917482420802
epoch = 47/100 , loss = 0.0015873076627030969
epoch = 48/100 , loss = 0.0015493445098400116
epoch = 49/100 , loss = 0.0014946949668228626
epoch = 50/100 , loss = 0.0017264166381210089
epoch = 51/100 , loss = 0.0017276539001613855
epoch = 52/100 , loss = 0.0017105643637478352
epoch = 53/100 , loss = 0.002009486546739936
epoch = 54/100 , loss = 0.0018039626302197576
epoch = 55/100 , loss = 0.0014858106151223183
epoch = 56/100 , loss = 0.0014766218373551965
epoch = 57/100 , loss = 0.001354825682938099
epoch = 58/100 , loss = 0.0016515213064849377
epoch = 59/100 , loss = 0.0017897135112434626
epoch = 60/100 , loss = 0.0020319486502557993
epoch = 61/100 , loss = 0.0014246440259739757
epoch = 62/100 , loss = 0.002111970679834485
epoch = 63/100 , loss = 0.0016026514349505305
epoch = 64/100 , loss = 0.001208722242154181
epoch = 65/100 , loss = 0.001249300898052752
epoch = 66/100 , loss = 0.001080336980521679
epoch = 67/100 , loss = 0.0012848322512581944
epoch = 68/100 , loss = 0.0013283970765769482
epoch = 69/100 , loss = 0.000991801731288433
epoch = 70/100 , loss = 0.0009900893783196807
epoch = 71/100 , loss = 0.0009649007115513086
epoch = 72/100 , loss = 0.0009868944762274623
epoch = 73/100 , loss = 0.001025545410811901
epoch = 74/100 , loss = 0.0010654303478077054
epoch = 75/100 , loss = 0.0012418815167620778
epoch = 76/100 , loss = 0.0010207844898104668
epoch = 77/100 , loss = 0.0011799957137554884
epoch = 78/100 , loss = 0.0009445633040741086
epoch = 79/100 , loss = 0.0008851647726260126
epoch = 80/100 , loss = 0.0008838234352879226
epoch = 81/100 , loss = 0.0008626329363323748
epoch = 82/100 , loss = 0.000981785706244409
epoch = 83/100 , loss = 0.0008498949464410543
epoch = 84/100 , loss = 0.0007706452161073685
epoch = 85/100 , loss = 0.0007376892608590424
epoch = 86/100 , loss = 0.0007650668267160654
epoch = 87/100 , loss = 0.0007313430542126298
epoch = 88/100 , loss = 0.0007338047726079822
epoch = 89/100 , loss = 0.0007942364900372922
epoch = 90/100 , loss = 0.0010603038826957345
epoch = 91/100 , loss = 0.0008816437912173569
epoch = 92/100 , loss = 0.0007744330796413124
epoch = 93/100 , loss = 0.0007372246473096311
epoch = 94/100 , loss = 0.0006758462404832244
epoch = 95/100 , loss = 0.0006326730945147574
epoch = 96/100 , loss = 0.0006000517751090229
epoch = 97/100 , loss = 0.0005955364322289824
epoch = 98/100 , loss = 0.0006119828904047608
epoch = 99/100 , loss = 0.0005887396400794387

In [33]:
len(train_loader)

23

In [35]:
print(model)

ANN(
  (model): Sequential(
    (0): Linear(in_features=34, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=7, bias=True)
  )
)

In [36]:
print(list(model.parameters()))  # best weight & bias value

[Parameter containing:
tensor([[-0.2152, -0.0190,  0.0477,  ...,  0.0489, -0.0467,  0.1497],
        [ 0.1041,  0.1069, -0.1202,  ...,  0.1828, -0.1161, -0.0995],
        [ 0.0186, -0.0555, -0.3049,  ...,  0.1564,  0.1581,  0.1179],
        ...,
        [ 0.2578,  0.1695,  0.1563,  ..., -0.1431, -0.1884, -0.3403],
        [ 0.3149, -0.0440,  0.3177,  ..., -0.6315,  0.0769, -0.1273],
        [-0.0047,  0.1082,  0.0584,  ..., -0.2223,  0.1124,  0.0474]],
       requires_grad=True), Parameter containing:
tensor([ 0.2218,  0.0065,  0.0873,  0.1314,  0.0651,  0.3590,  0.1528,  0.0635,
         0.1203, -0.0505, -0.0038,  0.1072,  0.3660,  0.2802, -0.0021,  0.1854,
         0.1702,  0.1260,  0.0354,  0.2483,  0.3212, -0.1885,  0.0185,  0.0162,
         0.0863,  0.0540,  0.3716,  0.0876,  0.0942,  0.1860,  0.3006, -0.1536,
         0.0746,  0.0559, -0.1128,  0.0019,  0.0009, -0.0069,  0.0742,  0.2501,
         0.3377, -0.0631,  0.3480, -0.0607,  0.3996, -0.0367,  0.0764,  0.2327,
        -0.0107,  0.1394, -0.1380,  0.1028,  0.0387,  0.4038,  0.0552, -0.0892,
         0.1281, -0.0962,  0.2989,  0.0374,  0.1314,  0.0562,  0.2762,  0.3154],
       requires_grad=True), Parameter containing:
tensor([[ 0.0572,  0.0280,  0.0665,  ...,  0.0441,  0.4130,  0.0108],
        [-0.0954, -0.0026,  0.1285,  ..., -0.2334,  0.0016,  0.1677],
        [ 0.0423,  0.1861, -0.0557,  ...,  0.1573,  0.3482,  0.1730],
        ...,
        [-0.1346,  0.1653, -0.0732,  ...,  0.1639,  0.3131,  0.1242],
        [ 0.1759, -0.0918,  0.1635,  ...,  0.0905,  0.0079, -0.1020],
        [ 0.0467, -0.0444,  0.0435,  ...,  0.3812,  0.1263,  0.2130]],
       requires_grad=True), Parameter containing:
tensor([ 0.0656,  0.1495,  0.0999, -0.0294,  0.1254,  0.1939,  0.0612,  0.0902,
         0.1429,  0.1624,  0.2402,  0.1321,  0.1969,  0.0223, -0.0209,  0.0720,
        -0.0093, -0.0277,  0.0586,  0.2770,  0.0326,  0.1016,  0.0011,  0.0312,
         0.1680,  0.1520,  0.2088,  0.1593, -0.0246,  0.1017,  0.1281, -0.0450,
         0.1070,  0.0620,  0.2951,  0.0458,  0.1211,  0.0091,  0.1238,  0.2014,
         0.0130,  0.2249, -0.1069, -0.0943,  0.0104,  0.0203,  0.0924,  0.1899,
         0.2119,  0.1161,  0.0132, -0.0540,  0.0071,  0.0598,  0.1153,  0.0754,
         0.1892,  0.1528,  0.1181,  0.1473,  0.1114,  0.1685,  0.0309,  0.3390],
       requires_grad=True), Parameter containing:
tensor([[ 0.0347, -0.4039,  0.1546, -0.2118, -0.4159, -0.3474, -0.3980,  0.0932,
         -0.2653,  0.0205, -0.0356, -0.6204, -0.5061, -0.1583,  0.1354, -0.1455,
          0.2622, -0.0263, -0.0575, -0.2402, -0.0632, -0.3206, -0.4137,  0.3473,
         -0.4058, -0.0478, -0.2625, -0.3382, -0.0951, -0.5600, -0.3447, -0.4052,
          0.2334, -0.0401,  0.2973, -0.0780,  0.1317,  0.1201,  0.2666, -0.3590,
          0.1857, -0.1498, -0.1877,  0.2731, -0.2466,  0.0540, -0.5705, -0.0800,
         -0.6321, -0.0954, -0.1255, -0.0567,  0.1706, -0.3380, -0.6321,  0.3552,
          0.0740, -0.2620,  0.3366,  0.0694, -0.0790,  0.1569, -0.3350,  0.1694],
        [-0.0115, -0.0719, -0.1904, -0.3684,  0.0934,  0.1309, -0.8391, -0.4052,
          0.2612,  0.2547, -0.9845,  0.3276, -0.1037,  0.0554, -0.5594, -0.0871,
          0.0437,  0.2239, -0.5607,  0.1397, -0.0819,  0.3468,  0.2122, -0.0410,
          0.1854,  0.2606,  0.1465,  0.9058, -0.0183, -0.0225,  0.1958,  0.1096,
          0.2972, -0.3739, -0.5891,  0.0313,  0.0535, -0.5750, -0.0535,  0.0308,
         -0.1460,  0.0676,  0.7574, -0.0307,  0.3363,  0.1645,  0.2362, -0.0700,
          0.2049, -0.8709, -1.0663, -0.2548,  0.2098,  0.0632,  0.0486,  0.1186,
         -0.7424,  0.5119, -0.4177,  0.1738, -0.0323, -0.2513, -0.4858, -0.6582],
        [ 0.1335,  0.0383, -0.3226, -0.1338,  0.0854,  0.0424,  0.6117, -0.3552,
         -0.3731, -0.0793, -0.0580, -0.3473, -0.1675,  0.2113,  0.5145,  0.2763,
          0.1451, -0.0235, -0.1255, -0.2432,  0.2697, -0.4644,  0.0025,  0.2702,
          0.0226, -0.3879, -0.0804, -0.6200,  0.0588, -0.5159,  0.1179,  0.1266,
         -0.6520,  0.2465,  0.0974,  0.0309, -0.5226,  0.3105,  0.1778, -0.4612,
          0.2197, -0.2724, -0.4334,  0.1878, -0.3469, -0.6207, -0.2593,  0.0998,
         -0.2927, -0.5205,  0.9090,  0.2599,  0.0974, -0.3234, -0.4943,  0.0957,
          0.2227, -0.5075, -0.0963, -0.5012,  0.2429, -0.1492,  0.1131, -0.2153],
        [ 0.1658, -0.2104,  0.0274,  0.3200, -0.3088, -0.8107,  0.2844, -0.0788,
         -0.3861, -0.3623, -0.4054,  0.2048,  0.1792, -0.0626,  0.1424, -0.0487,
         -0.6527,  0.1406, -0.2467, -0.1891, -0.0130,  0.3639, -0.3479, -0.2926,
         -0.4184, -0.0837, -0.3659, -0.2776, -0.0932,  0.2959, -0.2756,  0.0314,
          0.1228, -0.1263, -0.2788, -0.0329,  0.1454,  0.0636, -0.2956,  0.1678,
         -0.1229,  0.1044, -0.4710, -0.1142,  0.1708,  0.0609,  0.2007, -0.2285,
          0.1407, -0.4277, -0.1362, -0.1994, -0.2243,  0.2387, -0.1155, -0.6648,
          0.0403, -0.4957, -0.2921,  0.1236, -0.1368,  0.1876, -0.3430, -0.0410],
        [-0.0934,  0.2374, -0.1250, -0.3842, -0.5102, -0.2920, -0.1714,  0.2692,
          0.1113,  0.1703,  0.5252, -0.1641, -0.1186,  0.1047, -0.3169, -0.1176,
         -0.3805, -0.4043, -0.3295,  0.1256, -0.2609,  0.1631, -0.5170, -0.1942,
          0.0550, -0.2555,  0.1275, -0.7971, -0.1066, -0.7195,  0.1194, -0.6972,
         -0.2248, -0.4906,  0.2917, -0.0548, -0.1245, -0.3307, -0.5061,  0.2823,
         -0.3160,  0.1092,  0.0582, -0.6593,  0.2454, -0.3700, -0.0800, -0.5143,
          0.2866,  0.1955, -0.4944, -0.2191,  0.1106, -0.3165,  0.1957, -0.4522,
          0.1301,  0.1482,  0.1836,  0.2147, -0.3213,  0.1405, -0.0103,  0.2404],
        [ 0.1458,  0.1704,  0.0466, -0.2429, -0.3099, -0.2946, -0.1196,  0.1188,
          0.2155, -0.2110,  0.3389, -0.0122,  0.1028, -0.2245,  0.0919,  0.2460,
         -0.2491, -0.2599,  0.3568, -0.3163, -0.2141,  0.2112, -0.3147, -0.1238,
         -0.3602,  0.1864, -0.1675,  0.1632,  0.0272,  0.4202,  0.2542, -0.1363,
         -0.1835,  0.1395, -0.3078, -0.0899, -0.2540, -0.0230, -0.5025,  0.1931,
          0.1044, -0.2761,  0.2655, -0.2553,  0.2094,  0.1337,  0.1043, -0.1789,
          0.1875,  0.1372,  0.2221,  0.2252, -0.1080,  0.0466,  0.1685, -0.4364,
         -0.3926,  0.2361, -0.4906, -0.2525, -0.2129, -0.1190,  0.1650, -0.4544],
        [-0.9539, -0.1379, -0.3667,  0.2383, -0.1459,  0.3101,  0.6471,  0.0920,
         -0.0218, -0.1083, -0.2977,  0.1842,  0.1391, -0.3044, -0.4570, -0.3969,
          0.1769, -0.2511,  0.0729,  0.1371, -0.4563, -0.5616,  0.1644, -0.3848,
          0.2331, -0.1470,  0.0073, -0.8096, -0.0451, -0.3746, -0.3647, -0.1973,
         -0.1612,  0.3531,  0.0226, -0.0603,  0.1333,  0.0134,  0.2699,  0.0882,
         -0.0094,  0.2641, -0.7098, -0.0535, -0.4863,  0.0828, -0.1900,  0.3793,
         -0.0112,  0.7607,  0.3134,  0.0682, -0.2266,  0.3131,  0.0248,  0.0843,
          0.3460, -0.1038,  0.1842, -0.0973, -0.2474, -0.4553,  0.3416,  0.2876]],
       requires_grad=True), Parameter containing:
tensor([-0.0016,  0.0709, -0.1451,  0.0355,  0.1855,  0.0513,  0.1535],
       requires_grad=True)]

### Evaluation

In [46]:
model.eval()

total = 0
correct = 0  # correct pred

with torch.no_grad():

    for xb , yb in test_loader:
        output = model(xb) #Forward Propgation , pred value
        _, pred = torch.max(output,1) # torch.max - return max value and index
        # here pred = index
        # o/p  - 7 values [1, 0.6, 1.4 , 0.5 , -0.2 , 1.2, 0.1 ]
        #( max value = 1.4 , index = 2)

        correct += (pred == yb).sum().item()  # sum store for all batches

In [47]:
print(correct)

167

In [48]:
print(correct/180 *100)

92.77777777777779

In [39]:
print(yb.shape)

torch.Size([20])

In [40]:
y_test.shape

(180,)